(package "htmltagwrap"
         "0.0.3"
		 "Wraps a chunk of HTML code in tags")

(website-url "https://github.com/jcs-elpa/htmltagwrap")
(keywords "keybindings")

(package-file "htmltagwrap.el")

(source "melpa")

(depends-on "emacs" "24.4")

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
